### PR TITLE
Listen for EMPTYFOLDER message in RLS handling

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by andrecardoso** [comment]
@stulees per current local-storage-module implementation there's no "EMPTYFOLDER" message being sent. Is this something we need to implement?

**Comment by stulees** [comment]
@santiagonoguez @andrecardoso  This is based on a side conversation with @tejohnso . Discovered today that MS breaks when a folder is watched that is either empty or doesn't exist. @tejohnso mentioned correcting MS and then it would required LS to facilitate this new EMPTYFOLDER message based on MS result.

**Comment by andrecardoso** [comment]
@stulees @tejohnso is this message going to be sent when if the user deletes all the files of a watched folder?

**Comment by stulees** [comment]
@andrecardoso I _think_ this message will (and only needs to) be sent upon initial WATCH of the folder. If a user later deletes all files while Player is running, the Widget is going to know that there are no files left to display based on DELETED messages and thus display a message on screen.

**Pull request merged**
